name: Create and publish a production container
on:
  push:
    branches:
      - 'production'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag for this image build'
        required: true
        default: 'latest'
    
jobs:
  build-production:

    runs-on: ubuntu-latest
    env:
      PILLAR: staging
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Look for tag
      id: istagged
      run: echo "PILLAR=production" >> $GITHUB_ENV
    -
      name: Docker meta
      id: meta
      if: env.PILLAR == 'production'
      uses: docker/metadata-action@v3
      with:
        images: martinkey/price-fetching-service

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: martinkey
        password: ${{ secrets.DOCKER_SECRET }}
    - 
      name: Build and push with Tag (workflow triggered manually)
      uses: docker/build-push-action@v2
      if: env.PILLAR == 'production' && github.event_name == 'workflow_dispatch'
      with:
        context: "."
        push: true
        tags: martinkey/price-fetching-service:${{ github.event.inputs.image_tag }}, martinkey/price-fetching-service:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: PROFILE=${{ env.PILLAR }}
    -
      name: Build and push with Tag (workflow triggered by tag)
      uses: docker/build-push-action@v2
      if: env.PILLAR == 'production' && github.event_name == 'push'
      with:
        context: "."
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: PROFILE=${{ env.PILLAR }}